### ISSUE TITLE
Implement support for PYEGA3

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/ega-file-transfer-to-collab-jt#1]
Implement support for [pyega3](https://github.com/EGA-archive/ega-download-client) to download data from EGA

notes:
[docker container](https://quay.io/repository/biocontainers/pyega3)

**Comment by b-f-chan** [comment]
@edsu7 created the script on OICR side, but EGA side script has some issues

@edsu7 to report issues to EGA so they can fix (however might be a file-specific issue)

**Comment by b-f-chan** [comment]
This is now baked into the general data transfer workflow, can we close this?
